exchanges:
  - name: coinbase
    channels:
      - ticker

product_ids:
  - coin: "ETH-USD"
    aggregation:
      type: "volume"
      interval: 1
  - coin: "BTC-USD"
    aggregation:
      type: "volume"
      interval: 1
  - coin: "LTC-USD"
    aggregation:
      type: "volume"
      interval: 100
  - coin: "XRP-USD"
    aggregation:
      type: "volume"
      interval: 10000
