exchanges:
  - name: kraken
    channels:
      - trade

product_ids:
  - coin: "ETH-USD"
    aggregation:
      type: "tick imbalance"
      interval: 100
  - coin: "BTC-USD"
    aggregation:
      type: "tick imbalance"
      interval: 175
  - coin: "LTC-USD"
    aggregation:
      type: "tick imbalance"
      interval: 60
  - coin: "XRP-USD"
    aggregation:
      type: "tick imbalance"
      interval: 50
