exchanges:
  - name: kraken
    channels:
      - trade

product_ids:
  - coin: "ETH-USD"
    aggregation:
      type: "tick imbalance"
      interval: 50
  - coin: "BTC-USD"
    aggregation:
      type: "tick imbalance"
      interval: 80
  - coin: "LTC-USD"
    aggregation:
      type: "tick imbalance"
      interval: 20
  - coin: "XRP-USD"
    aggregation:
      type: "tick imbalance"
      interval: 30
