version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Support for Poetry
    registries:
      - pip
    # Directory for pyproject.toml
    directory: "/"
    open-pull-requests-limit: 10
    rebase-strategy: auto

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
