name: processing_trades
language: python
variables:
  - name: KAFKA_INPUT_TOPIC
    inputType: InputTopic
    description: Kafka input topic to read the raw trade data from.
    defaultValue: trade
    required: true
  - name: KAFKA_OUTPUT_TOPIC
    inputType: OutputTopic
    description: Output topic with tick imbalance ohlc candles
    defaultValue: tick_imbalance_bars_live
    required: true
dockerfile: Dockerfile
runEntryPoint: src/processing.py
defaultFile: src/processing.py
