models:
  - model: MultiLinearRegression
    model_args:
      prediction_horizon: 1
  - model: XGBoostModel
    model_args:
      prediction_horizon: 1
      learning_rate: 0.01
      max_depth: 5
      min_child_weight: 8
      subsample: 0.7
      colsample_bytree: 0.7
      gamma: 0.1
      num_boost_round: 300
      objective: reg:pseudohubererror
