temporal_features:
  - timeperiod: week day
  - timeperiod: month day
  - timeperiod: hour
  - timeperiod: minute

log_return:
  - n_bars: 1
  - n_bars: 5

rsi_indicator:
 rsi_timeperiod: 14

momentum_indicator:
  momentum_timeperiod: 14

volatility_indicator:
  volatility_timeperiod: 14

cumulative_price_change: {}
high_low_pct_range: {}
vwap: {}
average_trade_size: {}
accumulation_distribution_index: {}
moving_average:
  window: 3

ema:
  window: 10

skewness:
  window: 10

kurtosis:
  window: 10
