name: trade_producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    description: The kafka topic that will save the trade data
    defaultValue: trade
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: Whether we connect to Kraken Websocket for live data or Kraken API for historical data
    defaultValue: live
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
