name: trade_producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    description: The kafka topic that will save the trade data
    defaultValue: first_topic
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
