name: price_predictor
language: python
variables:
  - name: HOPSWORKS__PROJECT_NAME
    inputType: Secret
    description: Hopsworks project name
    defaultValue: PROJECT_NAME
    required: true
  - name: HOPSWORKS__API_KEY
    inputType: Secret
    description: Hopsworks API Key
    defaultValue: API_KEY
    required: true
  - name: COMET_ML__PROJECT_NAME
    inputType: Secret
    description: Comet ML project name
    defaultValue: COMET_ML__PROJECT_NAME
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
