name: backfill_pipeline

networks:
  redpanda_network:
    name: redpanda_network
    driver: bridge

services:
  trade-producer:
    build:
      context: ../services/trade_producer
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda:9092
      KAFKA_TOPIC: trades_historical
      LIVE_OR_HISTORICAL: historical
      LAST_N_DAYS: 3
    volumes:
      - ../logs:/app/logs

  procesing-trades:
    build:
      context: ../services/processing_trades
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda:9092
      KAFKA_INPUT_TOPIC: trades_historical
      KAFKA_OUTPUT_TOPIC: volume_bars_historical
      KAFKA_CONSUMER_GROUP: trade_to_volume_ohlc_historical

  kafka-to-feature-store:
    build:
      context: ../services/kafka_to_feature_store
    networks:
      - redpanda_network
    env_file:
      - ../services/kafka_to_feature_store/.env
      - ../services/kafka_to_feature_store/credentials.env
    environment:
      KAFKA_BROKER_ADDRESS: redpanda:9092
      INPUT_TOPIC: volume_bars_historical
      BUFFER_SIZE: 10
      LIVE_OR_HISTORICAL: historical
    volumes:
      - ../logs:/app/logs
