version: '3'

networks:
  redpanda_network:
    external: true

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/config # host:container Store config
      - prometheus-data:/prometheus # host:container Store metrics
    restart: unless-stopped
    command:
      - --config.file=/config/prometheus.yml
    networks:
      - redpanda_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - redpanda_network
