kafka:
  kakfka_broker_address: "redpanda:9092"
  kafka_topic: "trades"

exchanges:
  - name: coinbase
    product_ids:
      - "ETH/USD"
      - "BTC/USD"
      - "LTC/USD"
      - "XRP/USD"
    channels:
      - "trades"
  - name: kraken
    product_ids:
      - "ETH/USD"
      - "BTC/USD"
      - "LTC/USD"
      - "XRP/USD"
    channels:
      - "trade"
