kafka_broker_address: "localhost:19092"  # default localhost
kafka_topic: "trades"

exchanges:
  - name: coinbase
    product_ids:
      - "ETH-USD"
      - "BTC-USD"
      - "LTC-USD"
      - "XRP-USD"
    channels:
      - "ticker"
  - name: kraken
    product_ids:
      - "ETH/USD"
      - "BTC/USD"
      - "LTC/USD"
      - "XRP/USD"
    channels:
      - "trade"
