exchanges:
#  - name: coinbase
#    product_ids:
#      - "ETH-USD"
#      - "BTC-USD"
#      - "LTC-USD"
#      - "XRP-USD"
#    channels:
#      - "ticker"
  - name: kraken
    product_ids:
      - "ETH/USD"
      - "BTC/USD"
      - "LTC/USD"
      - "XRP/USD"
    channels:
      - "trade"

live_or_historical: live
last_n_days: 1
