name: kafka_to_feature_store
language: python
variables:
  - name: INPUT_TOPIC
    inputType: InputTopic
    description: KAFKA topic with the tick imbalance candles
    defaultValue: tick_imbalance_bars_live
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    description: Consumer group to read tick imbalance candles
    defaultValue: tick_imbalance_ohlc_consumer_group
    required: true
  - name: FEATURE_GROUP
    inputType: FreeText
    description: Feature group name for the online feature store
    defaultValue: online_ohlc_feature_group
    required: true
  - name: FEATURE_GROUP_VERSION
    inputType: FreeText
    description: Feature group version for the online feature store
    defaultValue: 1
    required: true
  - name: FEATURE_GROUP_PRIMARY_KEYS
    inputType: FreeText
    description: Online feature group primary key
    defaultValue: '["start_time"]'
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: Whether to load the data to online or offline feature store
    defaultValue: live
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
