name: kafka_to_feature_store
language: python
variables:
  - name: INPUT_TOPIC
    inputType: InputTopic
    description: KAFKA topic with the tick imbalance candles
    defaultValue: tick_imbalance_bars_live
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
