name: kafka_to_feature_store
language: python
variables:
  - name: INPUT_TOPIC
    inputType: InputTopic
    description: KAFKA topic with the tick imbalance candles
    defaultValue: tick_imbalance_bars_live
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    description: Consumer group to read tick imbalance candles
    defaultValue: tick_imbalance_ohlc_consumer_group
    required: true
  - name: FEATURE_GROUP
    inputType: FreeText
    description: Feature group name for the online feature store
    defaultValue: online_ohlc_feature_group
    required: true
  - name: FEATURE_GROUP_VERSION
    inputType: FreeText
    description: Feature group version for the online feature store
    defaultValue: 1
    required: true
  - name: FEATURE_GROUP_PRIMARY_KEYS
    inputType: FreeText
    description: Online feature group primary key
    defaultValue: '["start_time"]'
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: Whether to load the data to online or offline feature store
    defaultValue: live
    required: true
  - name: PROJECT_NAME
    inputType: Secret
    description: Hopsworks project name
    defaultValue: PROJECT_NAME
    required: true
  - name: API_KEY
    inputType: Secret
    description: Hopsworks API KEY
    defaultValue: API_KEY
    required: true
  - name: SAVE_EVERY_N_SEC
    inputType: FreeText
    description: Save buffer to online feature store every N seconds
    defaultValue: 600
  - name: CREATE_NEW_CONSUMER_GROUP
    inputType: FreeText
    description: 'Whether or not to create a new consumer group to read the data from kafka '
    defaultValue: True
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
